### ISSUE TITLE
Issue TOC: show only primary article's galleys

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/immersion#22]
The issue goes from OJS 2 (don't know exact details).
Issue page contains `$primaryGenreIds` array that can be used for this purpose. Compare `article_summary.tpl` with the same template from the default theme for details.

Consider making the same for other themes as well.

**Comment by Vitaliy-1** [comment]
@sssoz, do you want to take a look at this one?

**Comment by sssoz** [comment]
I can look at it today.

**Comment by Vitaliy-1** [comment]
@sssoz Thanks!

Can you also look if this issue appears for the search page?

**Comment by sssoz** [comment]
It’s fine, since the search page includes `article_summary.tpl`!
