### ISSUE TITLE
Undefined index: enabled in plugins/themes/immersion/ImmersionThemePlugin.inc.php on line 197

### ISSUE THREAD

**Issue by bricas** [pkp/immersion#45]
Occasionally seeing the following error in our logs:

```
Undefined index: enabled in plugins/themes/immersion/ImmersionThemePlugin.inc.php on line 197
```

The line in question: https://github.com/pkp/immersion/blob/master/ImmersionThemePlugin.inc.php#L197

**Comment by Vitaliy-1** [comment]
Thanks!
The referenced commit should resolve it. Feel free to reopen the issue if not.
