### ISSUE TITLE
Show association looks like deceased author indicator 

### ISSUE THREAD

**Issue by alexdryden** [pkp/immersion#59]
**Describe the bug**
The plus sign next to the author name used to show the author's affiliation looks like the cross or dagger symbol used to indicate that the author is deceased in many countries. 

**To Reproduce**
1. Publish and article where the author has an affiliation
2. Go to the article detail page and scroll to the author 
3. Plus sign next to author name 
<img width="763" alt="Screen Shot 2020-12-11 at 12 12 23 PM" src="https://user-images.githubusercontent.com/47127862/101933416-2b305900-3baa-11eb-8bf0-2ea6ba00bf56.png">

**Additional Context**
The editor that shared this concern with me indicated that the association is very strong in some countries/academic communities

**Comment by Vitaliy-1** [comment]
Hi @alexdryden,

Thanks for the report. You the first one mentioning this. I guess it depends on typography. In our journal, we use the symbol you mentioned but it looks quite different from the plus sign: https://e-medjournal.com/index.php/psp/article/view/240.

**Comment by NateWr** [comment]
Maybe try down arrow / up arrow. that's the pattern that we are using for expand/collapse in the submissions list in the editorial backend.
