### ISSUE TITLE
OpenID Provider integration

### ISSUE THREAD

**Issue by felixhelix** [pkp/immersion#71]
Hi, 
we just have setup the OpenID provider to allow users to login with their ORCID. 
However, OpenID login is only possible via the "register" page, not via the pop up login window: The pop-up window only allows for legacy registration. So users who have registered using their ORCID will have difficulties to log in to the site.

Possible Solutions:
a) add the OpenID Providers to the login pop-up window
b) disable the login pop-up window, so that users can only login via the "register" page.

OJS Version 3.3.0.8
Immersion Theme 1.1.0.0

Yours,
Felix

**Comment by Vitaliy-1** [comment]
Closing in favour of https://github.com/pkp/immersion/issues/72
