### ISSUE TITLE
Div sections are not shown in homepage

### ISSUE THREAD

**Issue by marcusealfa** [pkp/immersion#91]
**Describe the bug**
In homepage, a section that has been added in "website -> advanced -> additional contents" is not displayed properly. 
It seems like div statements are cut away.

**To Reproduce**
In the following static page, two columns (in the same line) are created through some div statements:
https://esperienzesociali.it/esperienzesociali/redazione

Unifortunatel, in homepage the same code does not work and the browser puts the two div statements one under the other:
https://esperienzesociali.it/esperienzesociali

**Expected behavior**
As in the first page (two columns, one aside the other)

**Desktop (please complete the following information):**
 - Browser: Brave
 - Version of OJS: 3.4.0.3

**Additional context**

**Comment by asmecher** [comment]
@marcusealfa, you can resolve this by applying either of the attached commits (they are equivalent).

**Comment by marcusealfa** [comment]
Thanks a lor, @asmecher. I've tried the commit but it does not do the trick. Please, have a look to our mainpage, the additional contents are still on different lines, while I need them on the same line. Thanks for your patience.

**Comment by asmecher** [comment]
@marcusealfa, I think that's just a styling/CSS question. Unless you add specific styling to a `<div>` element, it will not display inline.

**Comment by marcusealfa** [comment]
Dear @asmecher,
if I use this code in a static page, the elements are inline. If I use the same code in homepage, they are in column. 

```
<div class="page">

<div class="firstdiv" style="float: left; display: block; width: 205px; height: 300px;">
<p style="text-align: center;"><img src="https://esperienzesociali.it/public/site/images/esperienze_admin/redazione.jpg" alt="" width="200" height="200" /></p>
<p style="text-align: center;">fgdgdgdg</p>
</div>

<div class="secdiv" style="float: left; display: block; width: 205px; height: 300px;">
<p><img src="https://esperienzesociali.it/public/site/images/esperienze_admin/redazione.jpg" alt="" width="200" height="200" /></p>
<p style="text-align: center;">fgdgdgdg</p>
</div>

</div>
```

In particular, in homepage `<div class="firstdiv">` disappears and, in fact,`<p>` take the whole width of the "additional-home-content" so pushing `<div class="secdiv">` in the second line.

Have a look, `<div>` disappeards in homepage:

<img width="534" alt="image" src="https://github.com/pkp/immersion/assets/19575730/fd18dfae-a39d-4b17-8fb4-4fe54b3d8663">



while it's where it's expected to be in a static page:

<img width="635" alt="image" src="https://github.com/pkp/immersion/assets/19575730/c3a33966-39b7-41d8-8454-44ea3721b81b">

I don't know if this problem regards the Immersion theme or the way OJS renders the homepage, so please be so kind to help me out to understand why it happens and who I have to address to for solving it.

Thanks a lot.

**Comment by asmecher** [comment]
@marcusealfa, have you been able to resolve the problem? The two `<div>` elements appear side by side to me, when styled to do that.
